builder:
  track: dev

labels:
  app-group: ziplinee-ci-extensions
  team: ziplinee-team
  language: golang

version:
  semver:
    major: 0
    minor: 1

stages:
  build:
    image: golang:1.17-alpine
    env:
      CGO_ENABLED: 0
      GOOS: linux
    commands:
    - go test ./...
    - go build -a -installsuffix cgo -ldflags "-X main.appgroup=${ZIPLINEE_LABEL_APP_GROUP} -X main.app=${ZIPLINEE_GIT_NAME} -X main.version=${ZIPLINEE_BUILD_VERSION} -X main.revision=${ZIPLINEE_GIT_REVISION} -X main.branch=${ZIPLINEE_GIT_BRANCH} -X main.buildDate=${ZIPLINEE_BUILD_DATETIME}" -o ./publish/${ZIPLINEE_GIT_NAME} .

  bake:
    image: extensions/docker:dev
    action: build
    inline: |
      FROM scratch

      LABEL maintainer="ziplinee.io" \
            description="The ${ZIPLINEE_GIT_NAME} component is an Ziplinee extension to update build status in Bitbucket for builds handled by Ziplinee CI"

      COPY ca-certificates.crt /etc/ssl/certs/
      COPY ${ZIPLINEE_GIT_NAME} /

      ENV ZIPLINEE_LOG_FORMAT="console"

      ENTRYPOINT ["/${ZIPLINEE_GIT_NAME}"]
    container: bitbucket-status
    repositories:
    - extensions
    path: ./publish
    copy:
    - /etc/ssl/certs/ca-certificates.crt

  check-container:
    parallelStages:
      check-efficiency:
        image: extensions/docker:dev
        action: dive
        container: bitbucket-status
        repositories:
        - extensions

      vulnerability-scan:
        image: extensions/docker:dev
        action: trivy
        container: bitbucket-status
        repositories:
        - extensions

  push-to-docker-hub:
    image: extensions/docker:dev
    action: push
    container: bitbucket-status
    repositories:
    - extensions

  slack-notify:
    image: extensions/slack-build-status:stable
    workspace: ziplinee
    channels:
    - '#build-status'
    when:
      status == 'succeeded' ||
      status == 'failed'

releases:
  dev:
    triggers:
    - pipeline:
        name: self
        branch: .+
    stages:
      tag-container-image:
        image: extensions/docker:dev
        action: tag
        container: bitbucket-status
        repositories:
        - extensions
        tags:
        - dev

  beta:
    stages:
      tag-container-image:
        image: extensions/docker:dev
        action: tag
        container: bitbucket-status
        repositories:
        - extensions
        tags:
        - beta

      slack-notify:
        image: extensions/slack-build-status:stable
        workspace: ziplinee
        channels:
        - '#build-status'
        when:
          status == 'succeeded' ||
          status == 'failed'

  stable:
    stages:
      tag-container-image:
        image: extensions/docker:dev
        action: tag
        container: bitbucket-status
        repositories:
        - extensions
        tags:
        - stable
        - latest

      slack-notify:
        image: extensions/slack-build-status:stable
        workspace: ziplinee
        channels:
        - '#build-status'
        when:
          status == 'succeeded' ||
          status == 'failed'

  nanoserver-1809-dev:
    builder:
      os: windows
      track: nanoserver-1809-dev
    clone: true
    stages:
      build:
        image: ziplinee/golang:1.15.7-nanoserver-1809
        shell: cmd
        env:
          CGO_ENABLED: 0
          GOOS: windows
          GOARCH: amd64
        commands:
        - go build -v -ldflags "-X main.app=%ZIPLINEE_GIT_NAME% -X main.version=%ZIPLINEE_BUILD_VERSION% -X main.revision=%ZIPLINEE_GIT_REVISION% -X main.branch=%ZIPLINEE_GIT_BRANCH% -X main.buildDate=%ZIPLINEE_BUILD_DATETIME%" -o ./publish/%ZIPLINEE_GIT_NAME%.exe

      bake:
        image: extensions/docker:nanoserver-1809-dev
        action: build
        no-cache: true
        expand-variables: false
        container: bitbucket-status
        repositories:
        - extensions
        dockerfile: Dockerfile.nanoserver-1809
        path: ./publish

      push-to-docker-hub:
        image: extensions/docker:nanoserver-1809-dev
        action: push
        container: bitbucket-status
        repositories:
        - extensions
        tags:
        - nanoserver-1809-dev
        pushVersionTag: false

  nanoserver-1809-beta:
    builder:
      os: windows
      track: nanoserver-1809-dev
    clone: true
    stages:
      build:
        image: ziplinee/golang:1.15.7-nanoserver-1809
        shell: cmd
        env:
          CGO_ENABLED: 0
          GOOS: windows
          GOARCH: amd64
        commands:
        - go build -v -ldflags "-X main.app=%ZIPLINEE_GIT_NAME% -X main.version=%ZIPLINEE_BUILD_VERSION% -X main.revision=%ZIPLINEE_GIT_REVISION% -X main.branch=%ZIPLINEE_GIT_BRANCH% -X main.buildDate=%ZIPLINEE_BUILD_DATETIME%" -o ./publish/%ZIPLINEE_GIT_NAME%.exe

      bake:
        image: extensions/docker:nanoserver-1809-dev
        action: build
        no-cache: true
        expand-variables: false
        container: bitbucket-status
        repositories:
        - extensions
        dockerfile: Dockerfile.nanoserver-1809
        path: ./publish

      push-to-docker-hub:
        image: extensions/docker:nanoserver-1809-dev
        action: push
        container: bitbucket-status
        repositories:
        - extensions
        tags:
        - nanoserver-1809-beta
        pushVersionTag: false

  nanoserver-1809-stable:
    builder:
      os: windows
      track: nanoserver-1809-dev
    clone: true
    stages:
      build:
        image: ziplinee/golang:1.15.7-nanoserver-1809
        shell: cmd
        env:
          CGO_ENABLED: 0
          GOOS: windows
          GOARCH: amd64
        commands:
        - go build -v -ldflags "-X main.app=%ZIPLINEE_GIT_NAME% -X main.version=%ZIPLINEE_BUILD_VERSION% -X main.revision=%ZIPLINEE_GIT_REVISION% -X main.branch=%ZIPLINEE_GIT_BRANCH% -X main.buildDate=%ZIPLINEE_BUILD_DATETIME%" -o ./publish/%ZIPLINEE_GIT_NAME%.exe

      bake:
        image: extensions/docker:nanoserver-1809-dev
        action: build
        no-cache: true
        expand-variables: false
        container: bitbucket-status
        repositories:
        - extensions
        dockerfile: Dockerfile.nanoserver-1809
        path: ./publish

      push-to-docker-hub:
        image: extensions/docker:nanoserver-1809-dev
        action: push
        container: bitbucket-status
        repositories:
        - extensions
        tags:
        - nanoserver-1809-stable
        pushVersionTag: false
